### ISSUE TITLE
integrating with the Open canvas frontend.

### ISSUE THREAD

**Issue by Aamirshazad** [phy101/opencanvaspython#2]
It is not integrating with the Open canvas frontend. I have attempted several times, but I keep receiving an error. Could you help me solve this issue?

**Comment by statistica-ai** [comment]
Hello, indeed this version is not working yet., there are several bugs. I already fixed all the bugs but I didn't have time to commit it.

**Comment by Aamirshazad** [comment]
Could you please commit the changes when you have a moment? I need them urgently to continue my work.

Thanks in advance! Looking forward to your update.

**Comment by Aamirshazad** [comment]
> Hello, indeed this version is not working yet., there are several bugs. I already fixed all the bugs but I didn't have time to commit it.
If you don’t have time, please let me know where the error exactly is so I can try to solve it myself.

**Comment by Aamirshazad** [comment]
> Hello, indeed this version is not working yet., there are several bugs. I already fixed all the bugs but I didn't have time to commit it.
If you have some time now, please update it. I’ve been trying to resolve the issues in this code for a month, but I’m still unable to fully correct the errors.

Actually, I am using this for my university project, and the deadline is approaching. I would be very grateful if you could help with the update.

**Comment by Aamirshazad** [comment]
> Hello, indeed this version is not working yet., there are several bugs. I already fixed all the bugs but I didn't have time to commit it.



If you have some time now, please update it. I’ve been trying to resolve the issues in this code for a month, but I’m still unable to fully correct the errors.
Actually, I am using this for my university project, and the deadline is approaching. I would be very grateful if you could help with the update.

**Comment by statistica-ai** [comment]
The bugs are twofold. You have to match camelCase (typescript) with snake_Case (python). Everything should be in camelCase:

For example: web_search_results should the webSearchResults everywhere (do it for all state variables and all variables that related with the frontend)

On top of that, there some issue with dict and pydantic types, the easiest (not elegant) fix is check all cases.

        # Find the most recent human message
        recent_human = None
        for msg in reversed(state.get('_messages', [])):
            # Check if it's a HumanMessage object
            if hasattr(msg, 'type') and msg.type == "human":
                recent_human = msg
                break
            # Check if it's a dict with role="user"
            elif isinstance(msg, dict) and msg.get("role") == "user":
                recent_human = msg
                break
            # Check if it's a message with role="user"
            elif hasattr(msg, 'role') and msg.role == "user":
                recent_human = msg
                break
        
        if not recent_human:
            logger.warning("No recent human message found")
            return None
        
        # Get content from recent human message safely
        recent_content = ""
        if isinstance(recent_human, dict):
            recent_content = recent_human.get('content', '')
        elif hasattr(recent_human, 'content'):
            recent_content = recent_human.content
        else:
            logger.warning(f"Could not extract content from recent human message: {type(recent_human)}")
            return None

Finally, tool schema might need some adjustments. 

Unfortunately, I don't have time to fix this repo now, I also have deadlines to meet for unrelated projects and it is not a simple upload. But I can attest that will be fully functional python version with those fixes.
